#!/bin/sh

if [ -e /var/jb/Library/MobileSubstrate/DynamicLibraries/bfdecrypt_fromprefs.plist ]; then
    echo "bfdecrypt updated/reinstalled, updating tweak inject filter from preferences"
    cp /var/jb/Library/MobileSubstrate/DynamicLibraries/bfdecrypt_fromprefs.plist /var/jb/Library/MobileSubstrate/DynamicLibraries/bfdecrypt.plist
fi

if [ ! -e /var/jb/Library/MobileSubstrate/DynamicLibraries/bfdecrypt_fromprefs.plist ]; then
	echo "First time installing bfdecrypt"
    cp /var/jb/Library/MobileSubstrate/DynamicLibraries/bfdecrypt.plist /var/jb/Library/MobileSubstrate/DynamicLibraries/bfdecrypt_fromprefs.plist
    chown mobile:wheel /var/jb/Library/MobileSubstrate/DynamicLibraries/bfdecrypt_fromprefs.plist
    chmod 644 /var/jb/Library/MobileSubstrate/DynamicLibraries/bfdecrypt_fromprefs.plist
fi

chown mobile:wheel /var/jb/Library/MobileSubstrate/DynamicLibraries/bfdecrypt.plist
chmod 644 /var/jb/Library/MobileSubstrate/DynamicLibraries/bfdecrypt.plist
